---
title: "**Actividad 331**"
author: "dgonzalez"
subtitle: " " 
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# **Descripción actividad **

<br/><br/>

### <span style="color:#BC2B6A">**Grupo A : Construir un  poster** </span>
 
### <span style="color:#6666FF">**Grupo B : Construir un  video** </span> 

<br/><br/>

Para cada uno de los modelos asignados que contenga sus principales caracteristicas

##### * Origen de la distribución

##### * Características principales : f(x), F(x), E[X], V[X], representación gráfica....

##### * Ejemplo con enunciado, solución y sintaxis en R

##### * Aplicaciones en el campo de las ingeniería, ciencias, economía, salud...

##### * Relaciones entre distribuciones univariadas.[(Artículo)](http://www.stat.rice.edu/~dobelman/courses/texts/leemis.distributions.2008amstat.pdf)

##### * Referencias bibliográficas 

<br/><br/><br/>

# **Asignación de distribuciones**

<br/><br/>

|Grupo       | Distribución 1|  Distribución 2       |
|:----------:|:--------------|:----------------------|
| Grupo 1    | nomal         |  geométrica           |
| Grupo 2    | exponencial   |  binomial             |
| Grupo 3    | lognormal     |  Poisson              |
| Grupo 4    | t-Student     |  binomial negativa    |
| Grupo 5    | gamma         |  hipergeometrica      |
| Grupo 6    | beta          |  Poisson              |
| Grupo 7    | Gumbel        |  binomial negativa    |
| Grupo 8    | Weibull       |  geométrica           |
| Grupo 9    | F             |  hipergeométrica      |
| Grupo 10   | ji-cuadrado   |  hipergeométrica      | 
| Grupo 11   | geométrica    |  Cauchy               |  
| Grupo 12   | hipergeométrica| gamma                |
| Grupo 13   | normal        | binomial              |
| Grupo 14   | geométrica    | uniforme continua     |
| Grupo 15   | Poisson       | exponencial           |



<br/><br/><br/>

# 300MAE005 - A

| Grupo   |                             |                                  |                        | 
|:--------|:----------------------------|:---------------------------------|:-----------------------|
| 1       | Juan Camilo Sánchez         | Juan Fernando Ríos               | Gian Marco Pantoja     |  
| 2       | Valeria Ríos                | María Alejandra Ortiz            |                        |  
| 3       | Valentina Sánchez           | Carlos Mauricio Ramírez          | Daniela Velasco        | 
| 4       | Manuela Valdés              | Lina María Mazo                  | Valentina Gutiérrez    |  
| 5       | Alejandra Otero Marín       | Esteban Castro Castro            | Santiago Portillo      | 
| 6       | Antonio Varona              | Juan David Rodríguez             | Camilo Tarazona        |  
| 7       | Santiago Astudillo          | Maria Kanaseki                   | Isabella Llanos        | 
| 9       | Juan Camilo Zúñiga          | Yuliam Obando                    | Nayerly Rojas          |  
| 10      | Samuel Morales              | Juan Fernando Barrera            | Brayan Portilla        |  
| 11      | José Arango Gutierrez       | Sara Lucia Arango Rubio          | Andres Ceron Borja     |  
| 12      | Sebastian Echeverry Lemos   | Isaac Grun Valencia              | Carlos Enrique Lenis Cruz|
| 13      | Juan Solano Amaya           | Marlon TRochez Ramirez           |                        |




<br/><br/>

# 300MAE005 - B

| Grupo   |                             |                                  |                        |
|:--------|:----------------------------|:---------------------------------|:-----------------------|
| 1       | Shalom Cassetta             | Juliana Figueroa                 | Isaac López            |   
| 2       | Andrés Felipe Rodríguez     | Daniel Santiago Lodnoño          | Marlon Montero         |   
| 3       | Miguel Bejarano             | David Mauricio Suarez            |                        |   
| 4       | Esteban Campo               | María Camila Cortez              | Ismael Perea           |  
| 5       | Felipe Palacio              | Santiago Grisales                |                        |   
| 6       | Juan Acosta                 | Maria del Mar Villaquiran        | Fabian Ledezma         |   
| 7       | Miguel Cumbalaza Christian  | Riascos Joan Sandoval            |                        |   
| 8       | Cristian Camilo Tabares     | Jean Paul Gonzalez               | Néstor José Lugo       |  
| 9       | Deivi Muñoz                 | Fabian Antoyne Garcia Gallego    |                        |   
|10       | Duvan Aristizabal Figueroa  | Jhoan Manuel Buitrago Chavez     | Victor Cañon Otiz      |   
|11       | Santiago Caicedo Rojas      | Dilan Correa Ortiz               | Juan José Gómez Gómez  |  
|12       | Maria Gomez Martinez        | Carlos Guerrero Betancourth      | Carlos Loaiza Cifuentes|   
|13       | Andres Loaiza Diaz          | Carlos Molina Rodriguez          | Cristian Riascos Ramirez|  
|14       | Juan Rivera Cabrera         | Alvaro Vargas Garcia             |                        |   





















